#!/bin/bash
#
# twat (thinkwatt):
# record power consumption, calculate average and create a gnuplot graph
#
# requires:
# tp_smapi (kernel module)
# gnuplot
#
# TO-DO:
# * clean-up function
# * support for non-thinkpads via /proc/acpi/battery (gotta find the /sys equivalent for that too)
# * add options for PNG output dir
# * add option for modifying title, e.g. with twat -t|--title
# * make output name per default the same as input name (?)
# * check if AC is plugged in

# plotting variables {{{
# powerfile - if you use an ultrabay accu and have no main accu plugged in you might need to change BAT0 to BAT1
# this is also a preparation for non-thinkpad support
POWERFILE=/sys/devices/platform/smapi/BAT0/power_now
# information for gnuplot. this is the place where you can rename the x/y-labels on your graph, give the graph a custom title and such
DATE=$(date +%Y-%m-%d,\ %T)
TITLE="power consumption of my thinkpad, created by thinkwatt on $DATE"
XLABEL="sec (seconds)"
YLABEL="W (Watt)"
TERMINAL="png"
# if you'd like custom titles for the graphs, here's where you do it
#TITLE1="your custom title for line1"
#TITLE2="for line2"
#TITLE3="for line 3"
# if you want to set a specific range for x/y-axis do it below
#YRANGE="[4000:16000]"
#XRANGE="[0:2000]"

# use $TDIR to have twat save files in a different directory.
# twat will save two files:
# 1) a .plt file (containing plot instructions) in case you want to reuse/modify it
# 2) a .png file (the plot graphic)
TDIR="/tmp/thinkwatt"
PLOTFILE="$TDIR/$$.plt"
PNGFILE=$$.png
# }}}

# utilities {{{
message() {
  cat << EOF
usage:	thinkwatt [ -r <seconds> | -p | -a ] file

options:	
	-r, --record	start recording the power consumption; optional: specify output file
			once the file is recorded you'll have the option to directly create a gnuplot graph from it
	-p, --plot	create a plot image from a data file
	-a, --average	calculate the average power consumption from a data file
	-h, --help	show this help text
	
examples:
	thinkwatt -r 300 /foo/bar/consumption.dat
	thinkwatt -r 900
EOF
  exit 1
}

errorout() { echo "error: $*" >&2; exit 1; }
# }}}

[[ $(lsmod | grep smapi) ]] || errorout 'please load the kernel module tp_smapi first.'

# record {{{
record() {

  local seconds="$1"
  
  local datafile="$2"
  
  [[ "$seconds" =~ ^[0-9]+$ ]] || errorout "please specify the time in seconds."
  #[[ "$datafile" ]] || errorout 'please specify a file to write to.'
  
  if [[ -f "$datafile" ]];then
    read -p "overwrite $datafile? y/n "
    [[ "$REPLY" = "y" ]] || exit 0
  fi

  local tmpfile1=/tmp/$$.dat
  touch "$tmpfile1"
  
  echo "recording power consumption for the next $seconds seconds"
  
  for ((i=0; i<=$seconds; i++));do
    sleep 1
    cat "$POWERFILE" >> "$tmpfile1"
  done

  # we strip the leading "-" from the data file
  sed -i 's/-//g' "$tmpfile1"
  
  local tmpfile=$TDIR/$$.dat
  cat "$tmpfile1" | awk '{print $1/1000}' > "$tmpfile"
  
  if [[ $datafile ]];then
    local dir=$(dirname "$datafile")
    local file=$(basename "$datafile")

    [[ -d "$dir" ]] || mkdir -p "$dir"
    
    outputfile="$datafile"
  
    mv "$tmpfile" "$datafile" && echo "recorded data succesfully written to $datafile"
  else
    local file=$(basename "$tmpfile")
    outputfile="$tmpfile"
  fi
  
  echo "average consumption during the last $seconds seconds was $(average $outputfile) W"
  
  read -p "do you want to create a graphic now, too? y/n "
  [[ "$REPLY" = "y" ]] && plot "$outputfile" || exit 0
  
  cleanup

}
# }}}

# calculate average {{{
average() {

  [[ "$@" ]] || errorout 'please specify a file to read from.'
  [[ -f "$@" ]] || errorout 'file not found.'
  
  awk 'BEGIN{s=0;}{s+=($1);}END{print s/NR;}' "$@"
}
# }}}

# cleanup {{{
cleanup() { # clean up at least some of the mess i make :P
  rm "$tmpfile1"
}

# make the plot file {{{
makeplotfile() {

  cat << EOF
# gnuplot file
# created by thinkwatt
# $DATE

set title "$TITLE"
set xlabel "$XLABEL"
set ylabel "$YLABEL"
set terminal $TERMINAL
set output "$PNGFILE"
EOF
[[ $YRANGE ]] && echo "set yrange $YRANGE"
[[ $XRANGE ]] && echo "set yrange $YRANGE"
echo 
if [[ $TITLE1 ]];then
  echo "plot \"$datfile\" using (\$1) with lines title \"$TITLE1\" lt 2, \\"
else
  echo "plot \"$datfile\" using (\$1) with lines lt 2, \\"
fi

if [[ $TITLE2 ]];then
  if [[ $avg ]];then
    echo "\"$datfile\" using (\$1) smooth bezier title \"$TITLE2\" lt 1, \\"
  else
    echo "\"$datfile\" using (\$1) smooth bezier title \"$TITLE2\" lt 1"
  fi
else
  if [[ $avg ]];then
    echo "\"$datfile\" using (\$1) smooth bezier lt 1, \\"
  else
    echo "\"$datfile\" using (\$1) smooth bezier lt 1"
  fi
fi

[[ $avg ]] && echo "$avg title \"$file (average, $avg W)\""

}
# }}}

# do the plotting
plot() {

  [[ -z $(find $(sed 's/:/ /g' <<<$PATH) 2>/dev/null | grep -is gnuplot) ]] && errorout 'you have to install gnuplot first'
 
  local datfile="$@"
  
  local dir=$(dirname "$datfile")
  local file=$(basename "$datfile")

  [[ "$datfile" ]] || errorout 'please specify a file to read from.'
  [[ -f "$datfile" ]] || errorout 'file not found.'

  [[ -z $TITLE1 ]] && local TITLE1="$file (actual)"
  [[ -z $TITLE2 ]] && local TITLE2="$file (trend)"
   
  local avg=$(average "$datfile" | cut -c1-4)
  
  [[ -d "$TDIR" ]] || mkdir -p "$TDIR"
  makeplotfile > "$PLOTFILE" || errorout 'failed writing plotfile'
  gnuplot "$PLOTFILE"

  echo "done. you can find the plot file in $TDIR"
  echo "graph saved in current working directory as $PNGFILE"

}

# parse options {{{
parse_options() {

  [[ -z "$1" ]] && message

  while [[ -n "$1" ]]; do
    case "$1" in
      -r|--record)  mode='record'	;;
      -p|--plot)    mode='plot'		;;
      -a|--average) mode='average'	;;
      -h|--help)    message		;;
      *)            args+=( "$1" )	;;
    esac
    shift
  done
}
# }}}

# main {{{
main() {

  case "$mode" in
    record)  record "${args[@]}"	;;
    average) average "${args[@]}"	;;
    plot)    plot "${args[@]}"		;;
    *)       errorout 'invalid mode. use -r, -p or -a.' ;;
  esac
  
}
# }}}

parse_options "$@"
main
